name: build image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_image:
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v2

      - name: Install required software
        run: sudo apt-get -y update && sudo apt-get -y install qemu-utils grub-pc

      - name: Build disk image
        run: |
          image_name="image.img"
          image_size="54542848"
          qemu-img create -f raw $image_name $image_size
          dev=$(sudo losetup -f -P --show $image_name)
          sudo ln -s ${dev}p1 ${dev}1
          sudo ln -s ${dev}p2 ${dev}2
          sed -i -e '139s/^/# /' -e '143s/^/# /' -e '152s/^/# /' -e '168s/^/# /' -e '189,190s/^/# /' installer.sh
          printf 'YeS\n' | sudo ./installer.sh $dev
          sudo losetup -d $dev
          sudo rm ${dev}1 ${dev}2
          cd part_data && sudo zip -r files.zip * && sudo mv files.zip .. && cd ..
          mv docs/README_image README
          sudo zip MultiOS-USB_image.zip $image_name files.zip README

      - uses: actions/upload-artifact@v2
        with:
          name: image
          path: MultiOS-USB_image.zip
